# Generated by Django 3.2.10 on 2022-07-13 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Socialusers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('userprofileimg', models.ImageField(upload_to='<django.db.models.fields.CharField>/profileimg')),
            ],
        ),
        migrations.CreateModel(
            name='Useruploadedimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadedimage', models.ImageField(upload_to='letsocial/<django.db.models.fields.related.ForeignKey>')),
                ('imageuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letssocial.socialusers')),
            ],
        ),
    ]
