# Generated by Django 3.2.10 on 2022-07-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letssocial', '0002_auto_20220713_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postuser', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='useruploadedimage',
            name='uploadedimage',
            field=models.ImageField(upload_to='letsocial/user/'),
        ),
    ]
