# Generated by Django 3.2.10 on 2022-07-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letssocial', '0003_auto_20220721_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='userposts',
            name='postimages',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
