# Generated by Django 3.2.10 on 2022-07-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letssocial', '0004_userposts_postimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='userposts',
            name='posttext',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
