# Generated by Django 3.2.10 on 2022-07-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letssocial', '0005_userposts_posttext'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userprofileimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileimgusername', models.CharField(default='', max_length=100)),
                ('uploadedprofileimage', models.ImageField(upload_to='letsocial/userprofileimages/')),
            ],
        ),
        migrations.AlterField(
            model_name='useruploadedimage',
            name='uploadedimage',
            field=models.ImageField(upload_to='letsocial/usersgallery/'),
        ),
    ]
