# Generated by Django 3.2.10 on 2022-07-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letssocial', '0006_auto_20220724_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userdescriptiondetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('userdesc', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Socialusers',
        ),
    ]
