# Generated by Django 3.2.10 on 2022-08-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letssocial', '0011_alter_friendrequestbyuser_approvername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequestbyuser',
            name='approvername',
            field=models.CharField(default='', max_length=300),
        ),
    ]
