# Generated by Django 3.2.10 on 2022-08-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letssocial', '0012_alter_friendrequestbyuser_approvername'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequestbyuser',
            name='userwhorequest',
            field=models.CharField(default='', max_length=300),
        ),
    ]
