# Generated by Django 3.2.10 on 2022-08-17 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('letssocial', '0014_alter_friendrequestbyuser_approvestatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usercomments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personwhocomment', models.CharField(default='', max_length=100)),
                ('commenttext', models.CharField(default='', max_length=500)),
                ('commentonpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letssocial.userposts')),
            ],
        ),
    ]
