# Generated by Django 3.2.10 on 2022-08-25 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('letssocial', '0015_usercomments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Replycomments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personwhoreply', models.CharField(default='', max_length=100)),
                ('replycommenttext', models.CharField(default='', max_length=500)),
                ('replyoncomment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letssocial.usercomments')),
            ],
        ),
    ]
