# Generated by Django 3.2.10 on 2022-08-26 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letssocial', '0016_replycomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='replycomments',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 26, 12, 41, 3, 292092)),
        ),
        migrations.AddField(
            model_name='usercomments',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 26, 12, 41, 3, 291092)),
        ),
    ]
