# Generated by Django 3.2.10 on 2022-08-26 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letssocial', '0017_auto_20220826_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replycomments',
            name='pub_date',
            field=models.DateTimeField(default=datetime.date(2022, 8, 26)),
        ),
        migrations.AlterField(
            model_name='usercomments',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 26, 21, 42, 21, 659388)),
        ),
    ]
