# Generated by Django 3.2.10 on 2022-08-26 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letssocial', '0018_auto_20220826_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomments',
            name='pub_date',
            field=models.DateTimeField(default=datetime.date(2022, 8, 26)),
        ),
    ]
