# Generated by Django 3.2.10 on 2022-08-26 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letssocial', '0019_alter_usercomments_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replycomments',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 26, 21, 47, 34, 845073)),
        ),
        migrations.AlterField(
            model_name='usercomments',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 26, 21, 47, 34, 845073)),
        ),
    ]
