# Generated by Django 3.2.10 on 2022-09-16 20:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letssocial', '0020_auto_20220826_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Savechats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userwhomessage', models.CharField(default='', max_length=100)),
                ('otheruser', models.CharField(default='', max_length=100)),
                ('message', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='replycomments',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 17, 2, 7, 30, 637619)),
        ),
        migrations.AlterField(
            model_name='usercomments',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 17, 2, 7, 30, 637619)),
        ),
    ]
