# Generated by Django 3.2.10 on 2022-09-16 20:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('letssocial', '0021_auto_20220917_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='savechats',
            name='messagetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 16, 20, 40, 46, 282255, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='replycomments',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 17, 2, 10, 46, 282255)),
        ),
        migrations.AlterField(
            model_name='usercomments',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 17, 2, 10, 46, 282255)),
        ),
    ]
