# Generated by Django 3.2.10 on 2022-09-16 20:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('letssocial', '0022_auto_20220917_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='savechats',
            name='cgroupname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='replycomments',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 17, 2, 12, 44, 537487)),
        ),
        migrations.AlterField(
            model_name='savechats',
            name='messagetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 16, 20, 42, 44, 537487, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='usercomments',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 17, 2, 12, 44, 537487)),
        ),
    ]
