# Generated by Django 3.2.10 on 2022-09-19 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letssocial', '0029_auto_20220919_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replycomments',
            name='pub_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='savechats',
            name='messagetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='usercomments',
            name='pub_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
