# Generated by Django 3.2.10 on 2022-09-21 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letssocial', '0030_auto_20220919_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='savechats',
            name='messagedate',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='savechats',
            name='messagedatetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='savechats',
            name='messagetime',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
