# Generated by Django 3.2.10 on 2022-09-21 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letssocial', '0031_auto_20220921_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savechats',
            name='messagedate',
        ),
        migrations.RemoveField(
            model_name='savechats',
            name='messagetime',
        ),
    ]
