# Generated by Django 3.2.10 on 2022-09-21 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letssocial', '0032_auto_20220921_2109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savechats',
            old_name='messagedatetime',
            new_name='messagetime',
        ),
    ]
