# Generated by Django 3.2.10 on 2022-09-21 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letssocial', '0033_rename_messagedatetime_savechats_messagetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='savechats',
            name='messagedate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
